# Generated by Django 5.1.7 on 2025-04-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="fullname",
            new_name="username",
        ),
    ]
