# Generated by Django 5.1.7 on 2025-04-01 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth_app", "0002_rename_fullname_userprofile_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="username",
            new_name="fullname",
        ),
    ]
