# Generated by Django 5.1.7 on 2025-03-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("fullname", models.CharField(max_length=100)),
            ],
        ),
    ]
