# Generated by Django 5.1.7 on 2025-03-27 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board_app", "0002_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Member",
        ),
    ]
