# Generated by Django 5.1.7 on 2025-03-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_app", "0003_rename_user_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="boards", to="board_app.member"
            ),
        ),
    ]
