# Generated by Django 5.1.7 on 2025-03-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_app", "0004_board_members"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
            ],
        ),
    ]
