# Generated by Django 5.1.7 on 2025-03-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_app", "0005_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="tickets",
            field=models.ManyToManyField(
                blank=True, related_name="boards", to="board_app.ticket"
            ),
        ),
    ]
