# Generated by Django 5.1.7 on 2025-03-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board_app", "0006_board_tickets"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Ticket",
            new_name="Task",
        ),
        migrations.RenameField(
            model_name="board",
            old_name="tickets",
            new_name="tasks",
        ),
    ]
