# Generated by Django 5.1.7 on 2025-03-27 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board_app", "0008_board_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="owner",
        ),
    ]
