# Generated by Django 5.1.7 on 2025-03-28 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_app", "0009_remove_board_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="board",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boards",
                to="board_app.board",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("to_do", "To Do"),
                    ("in_progress", "In Progress"),
                    ("done", "Done"),
                    ("review", "Review"),
                ],
                default="to_do",
                max_length=50,
            ),
        ),
    ]
