# Generated by Django 5.1.7 on 2025-03-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_app", "0010_task_board_task_description_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                default="medium",
                max_length=50,
            ),
        ),
    ]
