# Generated by Django 5.1.7 on 2025-03-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_app", "0011_task_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="due_date",
            field=models.DateField(default="2025-02-27"),
            preserve_default=False,
        ),
    ]
