# Generated by Django 5.1.7 on 2025-03-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_app", "0012_task_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
