# Generated by Django 5.1.7 on 2025-03-28 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_app", "0013_alter_task_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="board_tasks",
                to="board_app.board",
            ),
        ),
    ]
