# Generated by Django 5.1.7 on 2025-03-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board_app", "0015_alter_task_board"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="tasks",
        ),
    ]
