# Generated by Django 5.1.7 on 2025-03-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_app", "0017_alter_task_board"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("to-do", "To Do"),
                    ("in-progress", "In Progress"),
                    ("done", "Done"),
                    ("review", "Review"),
                ],
                default="to_do",
                max_length=50,
            ),
        ),
    ]
