# Generated by Django 5.1.7 on 2025-03-28 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_app", "0019_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_boards",
                to="board_app.member",
            ),
            preserve_default=False,
        ),
    ]
