# Generated by Django 5.1.7 on 2025-03-28 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_app", "0020_board_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="assignee",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks_assign",
                to="board_app.member",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="reviewer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="board_app.member",
            ),
            preserve_default=False,
        ),
    ]
