# Generated by Django 5.1.7 on 2025-03-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_app", "0021_task_assignee_task_reviewer"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="comments",
            field=models.TextField(blank=True, max_length=225, null=True),
        ),
    ]
