# Generated by Django 5.2 on 2025-04-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_app", "0027_task_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
