# Generated by Django 5.2 on 2025-05-08 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_app", "0028_alter_task_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who are members of this board",
                related_name="boards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="owner",
            field=models.ForeignKey(
                help_text="User who owns the board",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_boards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="title",
            field=models.CharField(help_text="Title of the board", max_length=50),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                help_text="User who wrote the comment",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(help_text="Text content of the comment"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Time when the comment was created"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="task",
            field=models.ForeignKey(
                help_text="Task this comment is related to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="board_app.task",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                help_text="User assigned to work on the task",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_task",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="board",
            field=models.ForeignKey(
                help_text="Board to which the task belongs",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="board_app.board",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="creator",
            field=models.ForeignKey(
                help_text="User who created the task",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Short description of the task",
                max_length=225,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(
                blank=True, help_text="Due date for the task", null=True
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                default="medium",
                help_text="Priority level of the task",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                help_text="User assigned to review the task",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("to-do", "To Do"),
                    ("in-progress", "In Progress"),
                    ("done", "Done"),
                    ("review", "Review"),
                ],
                default="to-do",
                help_text="Current status of the task",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(help_text="Title of the task", max_length=50),
        ),
    ]
